### ISSUE TITLE
Firefox 65 тормоза

### ISSUE THREAD

**Issue by artemidon** [vkomforte/vkomforte.github.io#10]
после обновления очень медленно работает mail.ru.  Переход по папкам почтового ящика занимает до 1 минуты.  При откате на 64 все нормально

**Comment by vkomforte** [comment]
Логина на mail.ru у меня нет, поэтому воспроизвести проблему не могу. 

Все выглядит вполне нормально, https://ip.mail.ru :

![vkomforte_2019-02-15_13-53-53](https://user-images.githubusercontent.com/28865788/52855332-c29d0000-3129-11e9-814a-e1b884ad5247.png)

**Comment by artemidon** [comment]
Сам сайт открывается с той же скоростью. Проблема возникает при переходе по письмам. В 64 письмо открывается мгновенно, а в 65 секунд 30-40 ничего не происходит и только потом открывается.

**Comment by artemidon** [comment]
Они там изменили что-то с безопасностью. может поэтому....

**Comment by artemidon** [comment]
Проверил черех Hoxx  VPN - все нормально, то есть проблема именно в плагине.

**Comment by vkomforte** [comment]
Сорри, но пока даже и не знаю как вам помочь.

**Comment by artemidon** [comment]
Ничего, вы и так сделали всем нам очень большой подарок этим плагином... Как-нить справимся :)

**Comment by artemidon** [comment]
Пока просто откатился на 64

**Comment by Feodor2** [comment]
Тоже проблема на аналоге палемуна 28.
