### ISSUE TITLE
Прокси не найден

### ISSUE THREAD

**Issue by JustOff** [vkomforte/vkomforte.github.io#2]
Один из прокси-серверов, который используется в вашем расширении (а именно `techinfocom-st5.net`) больше не существует, из-за чего периодически возникает ошибка "Прокси не найден".

**Comment by vkomforte** [comment]
Исправил в 706.26.2.

**Comment by GSi1ver** [comment]
Добрый день!Сегодня не получается войти на запрещённые в Укр. сайты(яндекс,мэил). 
Окно с ошибкой сообщает: 
Ошибка при установлении защищённого соединения
OCSP-сервер не имеет статуса этого сертификата.
------------------------------------------------------------------
Помогите решить проблему.
