### ISSUE TITLE
FF 55 

### ISSUE THREAD

**Issue by Drage25** [vkomforte/vkomforte.github.io#3]
Not work from FF 55 Vkomforte

**Comment by vkomforte** [comment]
This is known issue currently awaiting for [fix](https://bugzilla.mozilla.org/show_bug.cgi?id=1383748) from Mozilla.

**Comment by Drage25** [comment]
This is known issue currently awaiting for fix from Mozilla.
Так и шо теперь делать? Знать бы где эта шняга зарыта,поменял бы с 54 .
В смысле скрипт....

**Comment by vkomforte** [comment]
Увы, ошибка глубоко в си-шном коде Firefox, так что пока мозила не починит у себя то что поломала, ничего не поделать. Надеюсь они успеют до релиза.

**Comment by Drage25** [comment]
От дiдько...Я эту 55  еле до ума довел.Аддоны ставятся без проблем....без проверки И угрозы ,типа "устарел" тоже убрал..А тут такую "поганку завернули"....Та иде они на курац!

**Comment by vkomforte** [comment]
В сегодняшнем nightly 56 исправили, ждем аплифт в 55.

**Comment by Drage25** [comment]
56 ужасная. И  IDM нет интеграции . 56 максимум. 0.а1.Кстати, и frigate  упал..."Слава Украине!"
Никто не верит, что в 55 этот баг... В Ru-board просто издеваются...Пришлось поставить 56, IDM присобачил...Кое-как впихнул аддоны...Но невозможно портабл из 3 файлов сделать, теребите этих бетовцев....Успехов !

**Comment by vkomforte** [comment]
Исправление будет в завтрашнем 55 RC1.

**Comment by Drage25** [comment]
Не плохо.

**Comment by vkomforte** [comment]
Исправлено в https://ftp.mozilla.org/pub/firefox/candidates/55.0-candidates/build1/.

[RESOLVED FIXED in Firefox 55](https://hg.mozilla.org/releases/mozilla-beta/rev/993bfbae557c).

**Comment by vkomforte** [comment]
И спасибо @JustOff за обнаружение бага и помощь с взаимодействием с Mozilla :+1:
