### ISSUE TITLE
geekbrains.ru недоступен

### ISSUE THREAD

**Issue by gwynnbleiidd** [vkomforte/vkomforte.github.io#5]
Кажется и geekbrains попал под раздачу, он же mail.ru принадлежит.
Проверял через впн, открывает, можно занести в список :)

**Comment by muvahepaci** [comment]
Аналогичная ситуация, плюс проблема с https://2ch.hk/ который тоже принадлежит майл ру. Можно добавить.

**Comment by vkomforte** [comment]
К сожалению оператор используемых этим расширением прокси-серверов пропускает запросы только к фиксированному списку сайтов в который не входят ни geekbrains, ни 2ch. Используйте VPN или другие способы обхода.
