### ISSUE TITLE
Ошибка MOZILLA_PKIX_ERROR_OCSP_RESPONSE_FOR_CERT_MISSING

### ISSUE THREAD

**Issue by GSi1ver** [vkomforte/vkomforte.github.io#6]
Сегодня не получилось открыть яндекс,Vkontakte. 
Ошибка сообщает: Ошибка при установлении защищённого соединения
OCSP-сервер не имеет статуса этого сертификата.
Помогите решить проблему.

**Comment by vkomforte** [comment]
У прокси-серверов, используемых этим расширением, временная проблема с сертификатами, через день-другой должно все пройти само собой. Если нужно срочно починить прямо сейчас, то зайдите в `about:config` и измените `security.ssl.enable_ocsp_stapling` на `false`. Только потом желательно вернуть обратно, когда ситуация с сертификатами прокси-серверов нормализуется.

**Comment by GSi1ver** [comment]
Огромное спасибо вам за вашу работу.

**Comment by vkomforte** [comment]
Сертификаты обновились, можно возвращать `security.ssl.enable_ocsp_stapling` обратно в `true`.
