### ISSUE TITLE
Firefox 63

### ISSUE THREAD

**Issue by evnibo** [vkomforte/vkomforte.github.io#7]
При установке на Firefox 63 пишет, что дополнение не совместимо :(

**Comment by vkomforte** [comment]
vkomforte56+.xpi без проблем устанавливается и работает на всех версиях вплоть до последнего доступного на сегодня 63.0a1 (2018-09-04) включительно.

**Comment by evnibo** [comment]
Упс извиняюсь, не увидел что там 2 версии на странице. Vkomforte56+.xp установилась. Спасибо, отличное расширение :)
